#!/bin/sh

function cleanup() {
  if test -d "$1"; then
    prev=$(pwd)
    cd "$1"
    if test "$1" != "." && test -f cleanup; then
      prev_backup=$prev
      . cleanup
      prev=$prev_backup
    else
      rm -f Makefile
      rm -f Makefile.in
      rm -f aclocal.m4
      rm -f config.*
      rm -f configure
      rm -f depcomp
      rm -f install-sh
      rm -f ltmain.sh
      rm -f makefiles.*~
      rm -f mdate-sh
      rm -f missing
      rm -f libtool
      rm -f stamp-h1
      rm -f *.o *.a *.la *.lo *.obj *.lib *.exe *.dll
      rm -fR autom4te.cache
      rm -fR .deps
      rm -fR .libs
    fi
    cd $prev
  fi
}

cleanup .
cleanup hello
cleanup echo
cleanup hello++
cleanup echo++
cleanup ltdl
cleanup instantGNU_ltdl
