#!/bin/bash

function cleanup() {
  rm -f Makefile
  rm -f Makefile.in
  rm -f aclocal.m4
  rm -f config.*
  rm -f configure
  rm -f depcomp
  rm -f install-sh
  rm -f ltmain.sh
  rm -f makefiles.*~
  rm -f mdate-sh
  rm -f missing
  rm -f libtool
  rm -f stamp-h1
  rm -f *.o *.a *.la *.lo *.obj *.lib *.exe *.dll
  rm -fR autom4te.cache
  rm -fR .deps
  rm -fR .libs
}

cleanup
if test -d include; then
  pushd include
  cleanup
  popd
fi
if test -d main; then
  pushd main
  cleanup
  popd
fi
if test -d libraries; then
  pushd libraries
  cleanup
  popd
fi
if test -d libltdl; then
  pushd libltdl
  cleanup
  popd
fi
rm -f libltdl/config/compile
rm -f libltdl/config/config.guess
rm -f libltdl/config/config.sub
rm -f libltdl/config/depcomp
rm -f libltdl/config/install-sh
rm -f libltdl/config/missing
rm -f libltdl/config/ltmain.sh
rm -f libltdl/m4/argz.m4
rm -f libltdl/m4/libtool.m4
rm -f libltdl/m4/ltdl.m4
rm -f libltdl/m4/ltoptions.m4
rm -f libltdl/m4/ltsugar.m4
rm -f libltdl/m4/ltversion.m4
rm -f libltdl/m4/lt~obsolete.m4
rm -f libltdl/COPYING.LIB
rm -f libltdl/README
rm -f libltdl/Makefile.am
rm -f libltdl/configure.ac
rm -f libltdl/aclocal.m4
rm -f libltdl/Makefile.in
rm -f libltdl/config-h.in
rm -f libltdl/configure
rm -f libltdl/argz_.h
rm -f libltdl/argz.c
rm -f libltdl/argz.h
rm -f libltdl/loaders/dld_link.c
rm -f libltdl/loaders/dlopen.c
rm -f libltdl/loaders/dyld.c
rm -f libltdl/loaders/load_add_on.c
rm -f libltdl/loaders/loadlibrary.c
rm -f libltdl/loaders/shl_load.c
rm -f libltdl/lt__dirent.c
rm -f libltdl/lt__strl.c
rm -f libltdl/libltdl/lt__alloc.h
rm -f libltdl/libltdl/lt__dirent.h
rm -f libltdl/libltdl/lt__glibc.h
rm -f libltdl/libltdl/lt__private.h
rm -f libltdl/libltdl/lt__strl.h
rm -f libltdl/libltdl/lt_dlloader.h
rm -f libltdl/libltdl/lt_error.h
rm -f libltdl/libltdl/lt_system.h
rm -f libltdl/libltdl/slist.h
rm -f libltdl/loaders/preopen.c
rm -f libltdl/lt__alloc.c
rm -f libltdl/lt_dlloader.c
rm -f libltdl/lt_error.c
rm -f libltdl/ltdl.c
rm -f libltdl/ltdl.h
rm -f libltdl/slist.c
